default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  port: 3000

development:
  <<: *default
  database: example_development

test:
  <<: *default
  database: example_development
